# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hX9ruywoN-HZ_XxlvvffusofGFXvVF0D
"""

!pip install ultralytics opencv-python numpy supervision roboflow pytube -q
!apt-get install ffmpeg -qq

import os
import cv2
import numpy as np
from ultralytics import YOLO
from google.colab import files
from google.colab.patches import cv2_imshow
from google.colab import drive
import matplotlib.pyplot as plt
from IPython.display import Video
import zipfile
import shutil
from datetime import datetime

print("✅ Setup complete!")

# SIMPLIFIED VERSION - No Drive Mount Required
# Just create local folders in Colab

print("📁 Creating local project folders...")
!mkdir -p /content/potato_counter/dataset
!mkdir -p /content/potato_counter/models
!mkdir -p /content/potato_counter/output
!mkdir -p /content/potato_counter/frames
print("✅ Local folders created!")

# To save files permanently, you can download them at the end

# ==================================================
# CELL 3 (Alternative): Simple Path Version
# ==================================================
# Just set the path without copying

import os
import cv2
from google.colab.patches import cv2_imshow

print("📁 Enter the path to your video file")

# Get the video path from user
video_path = input("Video path: ").strip()

# Check if file exists
if not os.path.exists(video_path):
    print(f"❌ Error: File not found at {video_path}")
else:
    video_filename = os.path.basename(video_path)

    # Display video information
    cap = cv2.VideoCapture(video_path)
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    duration = total_frames / fps if fps > 0 else 0

    print(f"\n📹 Video Information:")
    print(f"   Filename: {video_filename}")
    print(f"   Resolution: {width} x {height}")
    print(f"   FPS: {fps}")
    print(f"   Total frames: {total_frames}")
    print(f"   Duration: {duration:.2f} seconds")

    # Show first frame
    ret, first_frame = cap.read()
    if ret:
        print("\n🎬 First frame preview:")
        cv2_imshow(first_frame)
    cap.release()

    print(f"\n✅ Using video at: {video_path}")

# ==================================================
# Diagnostic Cell: Understand Your Camera Setup
# ==================================================

def analyze_camera_setup(video_path):
    """Help you understand where to place the counting line"""

    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    height, width = frame.shape[:2]

    print("\n🔍 CAMERA SETUP ANALYSIS")
    print("=" * 50)
    print("Watch a few seconds of video and answer:")
    print("\n1. Where do bags FIRST appear?")
    print("   a) Left side of frame")
    print("   b) Right side of frame")
    print("   c) Top of frame")
    print("   d) Bottom of frame")

    appear = input("Your answer (a/b/c/d): ").lower()

    print("\n2. When bags go INTO cold storage, they:")
    print("   a) Disappear on left side")
    print("   b) Disappear on right side")
    print("   c) Disappear at top")
    print("   d) Disappear at bottom")

    disappear = input("Your answer (a/b/c/d): ").lower()

    # Show frame with guidance
    cv2.putText(frame, "Watch where bags appear/disappear", (50, 50),
               cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2_imshow(frame)

    # Provide recommendation
    print("\n📋 RECOMMENDATION:")
    if appear in ['a', 'b'] or disappear in ['a', 'b']:
        print("✅ Use VERTICAL line at:")
        if appear == 'a' or disappear == 'b':
            print(f"   X coordinate: {width//4} (quarter of frame)")
            print("   Left side = Inside | Right side = Outside")
        else:
            print(f"   X coordinate: {3*width//4} (three-quarters of frame)")
            print("   Left side = Outside | Right side = Inside")
    else:
        print("✅ Use HORIZONTAL line at:")
        if appear == 'c' or disappear == 'd':
            print(f"   Y coordinate: {height//4}")
            print("   Top = Inside | Bottom = Outside")
        else:
            print(f"   Y coordinate: {3*height//4}")
            print("   Top = Outside | Bottom = Inside")

    cap.release()

# Run the diagnostic
analyze_camera_setup(video_path)

# ==================================================
# CELL 4 (Alternative - Stores inside_side globally)
# ==================================================

def setup_side_camera_counting(video_path):
    """Special setup for cameras on same wall as door"""

    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    height, width = frame.shape[:2]

    print("\n🎥 SIDE CAMERA COUNTING SETUP")
    print("=" * 60)
    print("Since your camera is on the same wall as the door:")
    print("\n1️⃣ We'll draw a VIRTUAL LINE where bags cross")
    print("2️⃣ Bags will appear on one side and disappear on the other")
    print("3️⃣ The line should be where bags are HALF in view")
    print("=" * 60)

    # Show sample frames with bags
    for i in range(3):
        cap.set(cv2.CAP_PROP_POS_FRAMES, i * 100)
        ret, frame = cap.read()
        if ret:
            cv2.putText(frame, "Bags appear/disappear near edges", (50, 50),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)
            cv2_imshow(frame)

    print("\n📏 Enter your VIRTUAL LINE coordinates:")
    print("   (This should be where bags cross from visible to invisible)")

    use_vertical = input("Is the line VERTICAL? (y/n): ").lower() == 'y'

    if use_vertical:
        x = int(input(f"X coordinate (0 to {width}): "))
        line_start = (x, 0)
        line_end = (x, height)
        print("\n🔄 Which side is INSIDE?")
        print(f"   Left of line (0 to {x}) OR Right of line ({x} to {width})")
        inside_side = input("Enter 'left' or 'right': ").lower()
    else:
        y = int(input(f"Y coordinate (0 to {height}): "))
        line_start = (0, y)
        line_end = (width, y)
        print("\n🔄 Which side is INSIDE?")
        print(f"   Above line (0 to {y}) OR Below line ({y} to {height})")
        inside_side = input("Enter 'above' or 'below': ").lower()

    cap.release()

    return line_start, line_end, inside_side

# Run setup - now expecting 3 values
line_start, line_end, inside_side = setup_side_camera_counting(video_path)
print(f"\n✅ Line coordinates saved: Start {line_start}, End {line_end}")
print(f"✅ Inside is: {inside_side} of the line")

# ==================================================
# CELL 6: Run Detection with Side Camera Counting Logic
# ==================================================
# This uses your line coordinates and inside_side from Cell 4

print("🚀 Starting bag detection with side-camera logic...")

# Load YOLOv8 model
model = YOLO('yolov8n.pt')  # 'n' for nano (fastest), 's' for small, 'm' for medium

# Open video
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# Setup video writer
output_path = "/content/potato_counter/output/side_camera_count.mp4"
out = cv2.VideoWriter(output_path,
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      fps, (width, height))

# Initialize counters
in_count = 0
out_count = 0
tracked_objects = {}  # Store previous positions {track_id: (x, y)}
frame_count = 0

# Determine if line is vertical or horizontal
is_vertical = (line_start[0] == line_end[0])  # Same X coordinate = vertical line
print(f"\n📏 Line orientation: {'Vertical' if is_vertical else 'Horizontal'}")
print(f"📍 Inside is {inside_side} of the line")

print("\n🔄 Processing video...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run detection and tracking
    results = model.track(frame, persist=True, conf=0.3, iou=0.5, verbose=False)

    # Draw counting line
    cv2.line(frame, line_start, line_end, (0, 255, 255), 3)

    # Add labels showing inside/outside
    if is_vertical:
        cv2.putText(frame, f"INSIDE ({inside_side})", (10, 30),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.putText(frame, "OUTSIDE", (width - 150, 30),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    else:
        if inside_side == "above":
            cv2.putText(frame, "INSIDE (above)", (10, 60),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.putText(frame, "OUTSIDE (below)", (10, height - 30),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        else:
            cv2.putText(frame, "OUTSIDE (above)", (10, 60),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
            cv2.putText(frame, "INSIDE (below)", (10, height - 30),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

    # Display counts
    cv2.putText(frame, f'IN: {in_count}  OUT: {out_count}',
                (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.putText(frame, f'Frame: {frame_count}/{total_frames}',
                (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

    # Process tracked objects
    if results[0].boxes.id is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        track_ids = results[0].boxes.id.cpu().numpy()
        confidences = results[0].boxes.conf.cpu().numpy()

        for box, track_id, conf in zip(boxes, track_ids, confidences):
            x1, y1, x2, y2 = box
            center = (int((x1 + x2) / 2), int((y1 + y2) / 2))

            # Draw bounding box
            cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), (255, 0, 0), 2)

            # Color code based on which side of line
            if is_vertical:
                if center[0] < line_start[0]:
                    color = (0, 255, 0) if inside_side == "left" else (0, 0, 255)
                else:
                    color = (0, 255, 0) if inside_side == "right" else (0, 0, 255)
            else:
                if center[1] < line_start[1]:
                    color = (0, 255, 0) if inside_side == "above" else (0, 0, 255)
                else:
                    color = (0, 255, 0) if inside_side == "below" else (0, 0, 255)

            # Draw colored dot at center
            cv2.circle(frame, center, 5, color, -1)
            cv2.putText(frame, f'ID: {int(track_id)}',
                       (int(x1), int(y1)-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

            # Check for line crossing
            if track_id in tracked_objects:
                prev_center = tracked_objects[track_id]

                if is_vertical:
                    # Vertical line crossing logic
                    line_x = line_start[0]
                    prev_x = prev_center[0]
                    curr_x = center[0]

                    # Crossed from left to right
                    if prev_x < line_x and curr_x >= line_x:
                        if inside_side == "left":
                            out_count += 1
                            print(f"📤 Bag {int(track_id)} EXITED at frame {frame_count} (Conf: {conf:.2f})")
                        else:
                            in_count += 1
                            print(f"📥 Bag {int(track_id)} ENTERED at frame {frame_count} (Conf: {conf:.2f})")

                    # Crossed from right to left
                    elif prev_x > line_x and curr_x <= line_x:
                        if inside_side == "left":
                            in_count += 1
                            print(f"📥 Bag {int(track_id)} ENTERED at frame {frame_count} (Conf: {conf:.2f})")
                        else:
                            out_count += 1
                            print(f"📤 Bag {int(track_id)} EXITED at frame {frame_count} (Conf: {conf:.2f})")

                else:
                    # Horizontal line crossing logic
                    line_y = line_start[1]
                    prev_y = prev_center[1]
                    curr_y = center[1]

                    # Crossed from above to below
                    if prev_y < line_y and curr_y >= line_y:
                        if inside_side == "above":
                            out_count += 1
                            print(f"📤 Bag {int(track_id)} EXITED at frame {frame_count} (Conf: {conf:.2f})")
                        else:
                            in_count += 1
                            print(f"📥 Bag {int(track_id)} ENTERED at frame {frame_count} (Conf: {conf:.2f})")

                    # Crossed from below to above
                    elif prev_y > line_y and curr_y <= line_y:
                        if inside_side == "above":
                            in_count += 1
                            print(f"📥 Bag {int(track_id)} ENTERED at frame {frame_count} (Conf: {conf:.2f})")
                        else:
                            out_count += 1
                            print(f"📤 Bag {int(track_id)} EXITED at frame {frame_count} (Conf: {conf:.2f})")

            # Update tracked position
            tracked_objects[track_id] = center

    # Write frame
    out.write(frame)
    frame_count += 1

    # Show progress every 100 frames
    if frame_count % 100 == 0:
        print(f"   Processed {frame_count}/{total_frames} frames... Current counts - IN: {in_count}, OUT: {out_count}")
        # Show a small preview
        preview = cv2.resize(frame, (640, 360))
        cv2_imshow(preview)

# Clean up
cap.release()
out.release()
print(f"\n✅ Processing complete!")
print(f"📊 Final counts - IN: {in_count}, OUT: {out_count}")
print(f"📁 Output saved to: {output_path}")

# ==================================================
# Summary Statistics
# ==================================================

print("\n" + "="*50)
print("📈 COUNTING SUMMARY")
print("="*50)
print(f"Total bags IN:  {in_count}")
print(f"Total bags OUT: {out_count}")
print(f"Net change:     {in_count - out_count}")
print(f"Total bags handled: {in_count + out_count}")

if in_count + out_count > 0:
    accuracy_estimate = "Good" if (in_count + out_count) > 10 else "Test run - need more data"
    print(f"Status: {accuracy_estimate}")

# ==================================================
# Optional: Save detailed log
# ==================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
log_file = f"/content/potato_counter/output/detailed_log_{timestamp}.txt"

with open(log_file, 'w') as f:
    f.write("POTATO BAG COUNTER DETAILED LOG\n")
    f.write("="*40 + "\n")
    f.write(f"Date/Time: {datetime.now()}\n")
    f.write(f"Video: {video_filename}\n")
    f.write(f"Video duration: {total_frames/fps:.2f} seconds\n")
    f.write(f"Counting line: {line_start} to {line_end}\n")
    f.write(f"Line orientation: {'Vertical' if is_vertical else 'Horizontal'}\n")
    f.write(f"Inside is: {inside_side} of line\n\n")
    f.write(f"FINAL COUNTS:\n")
    f.write(f"  Bags IN:  {in_count}\n")
    f.write(f"  Bags OUT: {out_count}\n")
    f.write(f"  Net change: {in_count - out_count}\n")

print(f"\n📄 Detailed log saved to: {log_file}")

# ==================================================
# CELL 4: Draw a Counting Zone (Rectangle)
# ==================================================
# Instead of a line, you'll draw a rectangle where bags are counted

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import ipywidgets as widgets
from IPython.display import display

def setup_counting_zone(video_path):
    """Let user draw a rectangle zone for counting"""

    cap = cv2.VideoCapture(video_path)
    ret, frame = cap.read()
    height, width = frame.shape[:2]

    print("\n🎯 ZONE-BASED COUNTING SETUP")
    print("=" * 60)
    print("You'll draw a RECTANGLE where bags will be counted")
    print("\n📌 How it works:")
    print("   1. Draw a rectangle around the area where bags appear/disappear")
    print("   2. When a bag ENTERS this zone → IN count +1")
    print("   3. When a bag EXITS this zone → OUT count +1")
    print("\n💡 For your side-camera setup:")
    print("   Draw the rectangle where bags FIRST become visible")
    print("   (where they appear from the door area)")
    print("=" * 60)

    # Show several frames to help choose zone
    print("\n📸 Sample frames to help you choose your zone:")
    for i in range(3):
        cap.set(cv2.CAP_PROP_POS_FRAMES, i * 150)
        ret, sample = cap.read()
        if ret:
            cv2.putText(sample, f"Frame {i*150}", (50, 50),
                       cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            cv2_imshow(sample)

    # Get zone coordinates from user
    print("\n✏️ Enter your counting zone coordinates:")
    print("   (Watch where bags appear and draw a box around that area)")

    x1 = int(input("Zone left X coordinate: "))
    y1 = int(input("Zone top Y coordinate: "))
    x2 = int(input("Zone right X coordinate: "))
    y2 = int(input("Zone bottom Y coordinate: "))

    # Show the zone on a frame
    cap.set(cv2.CAP_PROP_POS_FRAMES, 100)
    ret, preview = cap.read()
    if ret:
        # Draw rectangle
        cv2.rectangle(preview, (x1, y1), (x2, y2), (0, 255, 0), 3)
        cv2.putText(preview, "COUNTING ZONE", (x1, y1-10),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
        cv2.putText(preview, "Bags counted here", (x1, y2+30),
                   cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        print("\n👆 Your counting zone (green rectangle):")
        cv2_imshow(preview)

    cap.release()

    # Confirm zone
    confirm = input("\n✅ Does this zone look correct? (y/n): ").lower()
    if confirm != 'y':
        print("🔄 Let's try again. Run this cell again.")
        return None, None, None, None

    # Determine zone type based on your setup
    print("\n🔄 How should bags be counted?")
    print("   1. Count when bag ENTERS the zone (appears)")
    print("   2. Count when bag EXITS the zone (disappears)")
    print("   3. Count BOTH (enter = IN, exit = OUT)")

    count_mode = int(input("Enter 1, 2, or 3: "))

    return (x1, y1, x2, y2), count_mode

# Run the setup
zone_coords, count_mode = setup_counting_zone(video_path)

if zone_coords:
    x1, y1, x2, y2 = zone_coords
    print(f"\n✅ Zone saved: ({x1}, {y1}) to ({x2}, {y2})")
    print(f"✅ Counting mode: {count_mode}")
else:
    print("❌ Zone setup cancelled. Please run the cell again.")

# ==================================================
# CELL 6: Zone-Based Bag Counting
# ==================================================
# This counts bags when they enter/exit your defined zone

print("🚀 Starting ZONE-BASED bag counting...")

# Load YOLOv8 model
model = YOLO('yolov8n.pt')

# Open video
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# Setup video writer
output_path = "/content/potato_counter/output/zone_counting.mp4"
out = cv2.VideoWriter(output_path,
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      fps, (width, height))

# Unpack zone coordinates
x1, y1, x2, y2 = zone_coords

# Initialize tracking
tracked_objects = {}  # Stores {track_id: {'positions': [], 'in_zone': False, 'counted': False}}
in_count = 0
out_count = 0
frame_count = 0

print(f"\n📍 Counting Zone: ({x1}, {y1}) to ({x2}, {y2})")
print(f"📊 Counting mode: {count_mode} (1=Enter only, 2=Exit only, 3=Both)")
print("\n🔄 Processing video...")

def is_point_in_zone(point, x1, y1, x2, y2):
    """Check if a point is inside the zone"""
    x, y = point
    return x1 <= x <= x2 and y1 <= y <= y2

def get_zone_status(center, zone_coords):
    """Determine if object is in zone"""
    return is_point_in_zone(center, x1, y1, x2, y2)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run detection and tracking
    results = model.track(frame, persist=True, conf=0.3, iou=0.5, verbose=False)

    # Draw the counting zone
    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 3)
    cv2.putText(frame, "COUNTING ZONE", (x1, y1-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

    # Display counts
    cv2.putText(frame, f'IN: {in_count}  OUT: {out_count}',
                (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.putText(frame, f'Frame: {frame_count}/{total_frames}',
                (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

    # Process tracked objects
    if results[0].boxes.id is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        track_ids = results[0].boxes.id.cpu().numpy()
        confidences = results[0].boxes.conf.cpu().numpy()

        for box, track_id, conf in zip(boxes, track_ids, confidences):
            x1_box, y1_box, x2_box, y2_box = box
            center = (int((x1_box + x2_box) / 2), int((y1_box + y2_box) / 2))

            # Check if bag is in zone
            in_zone_now = get_zone_status(center, zone_coords)

            # Initialize tracking for new objects
            if track_id not in tracked_objects:
                tracked_objects[track_id] = {
                    'positions': [center],
                    'in_zone': in_zone_now,
                    'counted_in': False,
                    'counted_out': False,
                    'first_seen': frame_count
                }
            else:
                # Update position history
                tracked_objects[track_id]['positions'].append(center)
                # Keep last 10 positions for trajectory
                if len(tracked_objects[track_id]['positions']) > 10:
                    tracked_objects[track_id]['positions'].pop(0)

                prev_in_zone = tracked_objects[track_id]['in_zone']

                # Check for zone entry/exit
                if not prev_in_zone and in_zone_now:
                    # Bag ENTERED the zone
                    if count_mode in [1, 3] and not tracked_objects[track_id]['counted_in']:
                        in_count += 1
                        tracked_objects[track_id]['counted_in'] = True
                        print(f"📥 Bag {int(track_id)} ENTERED zone at frame {frame_count} (Conf: {conf:.2f})")

                        # Draw green highlight for entry
                        cv2.circle(frame, center, 10, (0, 255, 0), 2)
                        cv2.putText(frame, "ENTER", (center[0]+10, center[1]),
                                   cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

                elif prev_in_zone and not in_zone_now:
                    # Bag EXITED the zone
                    if count_mode in [2, 3] and not tracked_objects[track_id]['counted_out']:
                        out_count += 1
                        tracked_objects[track_id]['counted_out'] = True
                        print(f"📤 Bag {int(track_id)} EXITED zone at frame {frame_count} (Conf: {conf:.2f})")

                        # Draw red highlight for exit
                        cv2.circle(frame, center, 10, (0, 0, 255), 2)
                        cv2.putText(frame, "EXIT", (center[0]+10, center[1]),
                                   cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)

                # Update zone status
                tracked_objects[track_id]['in_zone'] = in_zone_now

            # Draw bounding box with color based on zone status
            if in_zone_now:
                # In zone - bright green
                color = (0, 255, 0)
                cv2.rectangle(frame, (int(x1_box), int(y1_box)), (int(x2_box), int(y2_box)), color, 2)
                cv2.putText(frame, f'ID:{int(track_id)} IN ZONE',
                           (int(x1_box), int(y1_box)-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
            else:
                # Out of zone - blue
                color = (255, 0, 0)
                cv2.rectangle(frame, (int(x1_box), int(y1_box)), (int(x2_box), int(y2_box)), color, 1)
                cv2.putText(frame, f'ID:{int(track_id)}',
                           (int(x1_box), int(y1_box)-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 1)

            # Draw center point
            cv2.circle(frame, center, 3, color, -1)

    # Write frame
    out.write(frame)
    frame_count += 1

    # Show progress
    if frame_count % 100 == 0:
        progress = (frame_count / total_frames) * 100
        print(f"   Progress: {progress:.1f}% - IN: {in_count}, OUT: {out_count}")

        # Show preview every 500 frames
        if frame_count % 500 == 0:
            preview = cv2.resize(frame, (640, 360))
            cv2_imshow(preview)

# Clean up
cap.release()
out.release()

print("\n" + "="*50)
print("✅ ZONE COUNTING COMPLETE!")
print("="*50)
print(f"📊 FINAL COUNTS:")
print(f"   Bags IN (entered zone):  {in_count}")
print(f"   Bags OUT (exited zone): {out_count}")
print(f"   Net change: {in_count - out_count}")
print(f"   Total bags tracked: {len(tracked_objects)}")
print("="*50)

# ==================================================
# Save Results
# ==================================================

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
results_file = f"/content/potato_counter/output/zone_counts_{timestamp}.txt"

with open(results_file, 'w') as f:
    f.write("POTATO BAG ZONE COUNTING RESULTS\n")
    f.write("="*40 + "\n")
    f.write(f"Date/Time: {datetime.now()}\n")
    f.write(f"Video: {video_filename}\n")
    f.write(f"Zone coordinates: ({x1},{y1}) to ({x2},{y2})\n")
    f.write(f"Counting mode: {count_mode}\n\n")
    f.write(f"Bags IN (entered zone):  {in_count}\n")
    f.write(f"Bags OUT (exited zone): {out_count}\n")
    f.write(f"Net change: {in_count - out_count}\n\n")
    f.write(f"Tracking statistics:\n")
    f.write(f"  Total unique bags tracked: {len(tracked_objects)}\n")
    f.write(f"  Average frames per bag: {total_frames/len(tracked_objects) if len(tracked_objects)>0 else 0:.1f}")

print(f"\n📄 Results saved to: {results_file}")

# ==================================================
# Display Video
# ==================================================

from IPython.display import Video
print("\n🎬 Processed video:")
display(Video(output_path, width=800))

# ==================================================
# Download Results
# ==================================================

download = input("\n📥 Download results? (y/n): ").lower()
if download == 'y':
    !zip -r /content/potato_counter_zone_results.zip /content/potato_counter/output/
    files.download('/content/potato_counter_zone_results.zip')
    print("✅ Download started!")

# ==================================================
# CELL A: Extract Frames for Training
# ==================================================
# Run this to get images from your video for labeling

import cv2
import os
from google.colab.patches import cv2_imshow
from google.colab import files
import zipfile

print("📸 EXTRACTING FRAMES FOR TRAINING")
print("="*50)

# Create folder for training images
!mkdir -p /content/potato_counter/training_images
!mkdir -p /content/potato_counter/training_images/all_frames

# Open video
cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

# Extract 1 frame every 2 seconds
extract_every_n_frames = fps * 2  # Every 2 seconds
frame_count = 0
saved_count = 0

print(f"📹 Video FPS: {fps}")
print(f"📊 Total frames: {total_frames}")
print(f"⏱️ Extracting 1 frame every 2 seconds...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    if frame_count % extract_every_n_frames == 0:
        # Save frame
        frame_path = f"/content/potato_counter/training_images/all_frames/frame_{saved_count:04d}.jpg"
        cv2.imwrite(frame_path, frame)
        saved_count += 1

        # Show progress every 50 frames
        if saved_count % 50 == 0:
            print(f"   Extracted {saved_count} frames so far...")

    frame_count += 1

cap.release()
print(f"\n✅ Extracted {saved_count} frames to: /content/potato_counter/training_images/all_frames/")

# Show sample frames
print("\n👀 Sample extracted frames:")
sample_frames = os.listdir("/content/potato_counter/training_images/all_frames/")[:3]
for i, frame_name in enumerate(sample_frames):
    frame = cv2.imread(f"/content/potato_counter/training_images/all_frames/{frame_name}")
    cv2_imshow(frame)

# Zip the frames for download
!zip -r /content/training_frames.zip /content/potato_counter/training_images/all_frames/
print("\n📥 Download these frames to label them:")
files.download('/content/training_frames.zip')