# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwsBIi8oU5MFejoGzoFakFyzBNmZPnFu
"""

# ==================================================
# CELL 1: Setup and Installation
# ==================================================

!pip install ultralytics opencv-python numpy roboflow -q

import os
import cv2
import numpy as np
from ultralytics import YOLO
from roboflow import Roboflow
from google.colab import files
from google.colab.patches import cv2_imshow
from google.colab import drive
from datetime import datetime
import shutil

print("✅ Setup complete!")

# Mount Drive
drive.mount('/content/drive')

# Create folders
!mkdir -p /content/potato_counter/models
!mkdir -p /content/potato_counter/output
!mkdir -p /content/potato_counter/test_images

print("✅ Folders created!")

# ==================================================
# CELL 2: Upload and Extract Your Dataset (FIXED for your structure)
# ==================================================

print("📤 UPLOAD YOUR DATASET")
print("="*50)
print("Upload your dataset ZIP file containing:")
print("  - train/")
print("  - valid/")
print("  - test/")
print("  - data.yaml")
print("  - README.roboflow")
print("="*50)

# Upload zip file
uploaded = files.upload()
zip_filename = list(uploaded.keys())[0]

# Create a temporary extraction directory
!mkdir -p /content/temp_extract

# Extract the zip
print(f"\n📦 Extracting {zip_filename}...")
!unzip -q "{zip_filename}" -d /content/temp_extract/

# Check what's inside the extraction
print("\n📁 Extracted contents:")
!ls -la /content/temp_extract/

# The files might be in a subfolder (often the zip contains a folder with the dataset name)
# Let's find where data.yaml is
import subprocess
result = subprocess.run(['find', '/content/temp_extract/', '-name', 'data.yaml', '-type', 'f'],
                       capture_output=True, text=True)
yaml_paths = result.stdout.strip().split('\n')

if yaml_paths and yaml_paths[0]:
    yaml_path = yaml_paths[0]
    print(f"\n✅ Found data.yaml at: {yaml_path}")

    # Get the directory containing data.yaml
    dataset_root = os.path.dirname(yaml_path)
    print(f"📁 Dataset root: {dataset_root}")

    # Create our project dataset folder
    !mkdir -p /content/potato_counter/dataset

    # Copy everything to our dataset folder
    !cp -r "{dataset_root}"/* /content/potato_counter/dataset/

    # Update the yaml path
    yaml_path = '/content/potato_counter/dataset/data.yaml'

    # Read and update data.yaml
    import yaml
    with open(yaml_path, 'r') as f:
        data_config = yaml.safe_load(f)

    print("\n📊 Original data.yaml content:")
    print(data_config)

    # Update paths for Colab
    data_config['path'] = '/content/potato_counter/dataset'
    data_config['train'] = 'train/images' if os.path.exists('/content/potato_counter/dataset/train/images') else 'train'
    data_config['val'] = 'valid/images' if os.path.exists('/content/potato_counter/dataset/valid/images') else 'valid'
    data_config['test'] = 'test/images' if os.path.exists('/content/potato_counter/dataset/test/images') else 'test'

    # Save updated yaml
    with open(yaml_path, 'w') as f:
        yaml.dump(data_config, f)

    print("\n✅ Updated data.yaml with Colab paths:")
    print(f"   path: {data_config['path']}")
    print(f"   train: {data_config['train']}")
    print(f"   val: {data_config['val']}")
    print(f"   names: {data_config.get('names', 'Not found')}")

    # Show dataset structure
    print("\n📁 Final dataset structure:")
    !ls -la /content/potato_counter/dataset/
    print("\n📁 Train folder:")
    !ls -la /content/potato_counter/dataset/train/ | head -10
    print("\n📁 Valid folder:")
    !ls -la /content/potato_counter/dataset/valid/ | head -10

else:
    print("\n❌ data.yaml not found!")
    print("\nShowing all extracted files:")
    !find /content/temp_extract/ -type f | head -30

# Clean up temp folder
!rm -rf /content/temp_extract/

print("\n✅ Dataset ready for training!")

# ==================================================
# CELL 3: Train Custom Model to Detect Men Carrying Bags
# ==================================================

print("👨 TRAINING MODEL TO DETECT MEN WITH BAGS")
print("="*50)
print(f"Classes: men_carrying_bag, men_without_bag")
print("Model will only COUNT men_carrying_bag")
print("This will take 1-2 hours. Let it run!")

# Load YOLO model
model = YOLO('yolov8n.pt')  # 'n' for nano (fastest)

# Train on your dataset
results = model.train(
    data=yaml_path,
    epochs=50,  # 50-100 epochs for good accuracy
    imgsz=640,
    batch=16,
    name='men_with_bags_model',
    device= 'cpu',  # Use GPU
    patience=10,  # Early stopping
    save=True,
    verbose=True
)

# Save the trained model
model_path = '/content/potato_counter/models/men_with_bags_detector.pt'
model.save(model_path)

# Backup to Google Drive
!cp {model_path} /content/drive/MyDrive/

print(f"\n✅ Model saved to: {model_path}")
print("✅ Backed up to Google Drive")

# ==================================================
# CELL 4: TEST YOUR IMPROVED MODEL
# ==================================================

# Load your NEW trained model (V2)
model = YOLO('/content/runs/detect/men_with_bags_model_v2/weights/best.pt')

print("🧪 TESTING IMPROVED MODEL")
print("="*50)
print("Class 0: men_carrying_bag (🟢 GREEN - COUNTED)")
print("Class 1: men_without_bag (🔴 RED - not counted)")
print("="*50)

# Find validation images
val_images_path = '/content/potato_counter/dataset/valid/images'

if os.path.exists(val_images_path):
    test_images = os.listdir(val_images_path)[:5]  # Test first 5 images

    for img_name in test_images:
        img_path = os.path.join(val_images_path, img_name)
        print(f"\n📸 Testing: {img_name}")

        # Test at normal confidence (0.25)
        results = model(img_path, conf=0.25)
        boxes = results[0].boxes

        if boxes is not None and len(boxes) > 0:
            print(f"   ✅ Found {len(boxes)} detections at confidence 0.25")
            for box in boxes:
                class_id = int(box.cls.cpu().numpy())
                conf = float(box.conf.cpu().numpy())
                class_name = "men_carrying_bag 🟢" if class_id == 0 else "men_without_bag 🔴"
                print(f"      - {class_name}: confidence {conf:.2f}")
        else:
            print(f"   ❌ No detections at confidence 0.25")

            # Try lower confidence
            results = model(img_path, conf=0.1)
            boxes = results[0].boxes
            if boxes is not None and len(boxes) > 0:
                print(f"   ✅ Found {len(boxes)} detections at confidence 0.1")
                for box in boxes:
                    class_id = int(box.cls.cpu().numpy())
                    conf = float(box.conf.cpu().numpy())
                    class_name = "men_carrying_bag 🟢" if class_id == 0 else "men_without_bag 🔴"
                    print(f"      - {class_name}: confidence {conf:.2f}")

        # Show image with detections
        annotated = results[0].plot()
        cv2_imshow(annotated)
else:
    print(f"❌ Validation images not found at {val_images_path}")

# ==================================================
# CELL 5: Upload Your Cold Storage Video
# ==================================================

print("📤 UPLOAD YOUR VIDEO FILE")
print("="*50)
print("Please upload the video from your cold storage camera")
print("Supported formats: MP4, AVI, MOV, MKV")
print("="*50)

from google.colab import files
import cv2
import shutil
from google.colab.patches import cv2_imshow
import os

# Upload video
uploaded = files.upload()

if len(uploaded) == 0:
    print("❌ No file uploaded. Please run this cell again.")
else:
    # Get the uploaded filename
    video_filename = list(uploaded.keys())[0]
    print(f"\n✅ Uploaded: {video_filename}")

    # Create a copy in our project folder
    !mkdir -p /content/potato_counter/videos
    video_path = f"/content/potato_counter/videos/input_{video_filename}"
    shutil.copy(f"/content/{video_filename}", video_path)

    # Get video information
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print("❌ Error: Could not open video file")
    else:
        # Get video properties
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        duration = total_frames / fps if fps > 0 else 0

        print(f"\n📹 VIDEO INFORMATION:")
        print(f"   Filename: {video_filename}")
        print(f"   Resolution: {width} x {height}")
        print(f"   FPS: {fps}")
        print(f"   Total Frames: {total_frames}")
        print(f"   Duration: {duration:.2f} seconds ({duration/60:.2f} minutes)")

        # Read and show first frame
        ret, first_frame = cap.read()
        if ret:
            print("\n🎬 FIRST FRAME PREVIEW:")
            # Resize for display if too large
            if width > 800:
                scale = 800 / width
                new_width = 800
                new_height = int(height * scale)
                first_frame = cv2.resize(first_frame, (new_width, new_height))
            cv2_imshow(first_frame)

        cap.release()

        # Save video info for later cells
        video_info = {
            'path': video_path,
            'filename': video_filename,
            'fps': fps,
            'width': width,
            'height': height,
            'total_frames': total_frames,
            'duration': duration
        }

        # Save to a file for other cells to read
        import pickle
        with open('/content/potato_counter/video_info.pkl', 'wb') as f:
            pickle.dump(video_info, f)

        print(f"\n✅ Video ready for processing!")
        print(f"   Path: {video_path}")

# Clean up original upload to save space
if os.path.exists(f"/content/{video_filename}"):
    os.remove(f"/content/{video_filename}")

# ==================================================
# CELL 6: Counting Method Setup (Using Your Coordinates)
# ==================================================

print("🎯 COUNTING METHOD SETUP")
print("="*50)
print("Your coordinates are ready!")
print("Line: [110,450] to [180,750]")
print("Zone: [23,424], [1371,416], [1352,1605], [11,1585]")
print("="*50)

# Choose counting method
print("\nWhich method would you like to use?")
print("1. LINE COUNTING (vertical line)")
print("2. ZONE COUNTING (polygon area)")

method = input("\nEnter 1 for LINE or 2 for ZONE: ").strip()

# Load video to show frame
import cv2
import pickle
import numpy as np
from google.colab.patches import cv2_imshow

# Load video info
with open('/content/potato_counter/video_info.pkl', 'rb') as f:
    video_info = pickle.load(f)

# Read first frame
cap = cv2.VideoCapture(video_info['path'])
ret, frame = cap.read()
cap.release()

if method == "1":
    # LINE COUNTING with your coordinates
    print("\n📏 Using LINE counting with your coordinates")

    # Your line coordinates
    x1, y1 = 110, 450
    x2, y2 = 180, 750

    line_start = (x1, y1)
    line_end = (x2, y2)

    print(f"\n📍 Line: {line_start} to {line_end}")

    # Determine direction
    print("\n🔄 Which direction is ENTERING the cold storage?")
    print("1. Left to Right crossing")
    print("2. Right to Left crossing")
    direction = input("Enter 1 or 2: ")
    enter_direction = "left_to_right" if direction == "1" else "right_to_left"

    counting_config = {
        'type': 'line',
        'start': line_start,
        'end': line_end,
        'enter_direction': enter_direction
    }

    # Draw line on frame
    cv2.line(frame, line_start, line_end, (0, 255, 255), 3)
    cv2.putText(frame, f"LINE - ENTER: {enter_direction}", (50, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2)

else:
    # ZONE COUNTING with your coordinates
    print("\n📦 Using ZONE counting with your coordinates")

    # Your zone coordinates (4 points)
    zone_points = np.array([[23,424], [1371,416], [1352,1605], [11,1585]], np.int32)
    zone_points = zone_points.reshape((-1, 1, 2))

    print(f"\n📍 Zone polygon with 4 points:")
    print(f"   Point 1: [23,424]")
    print(f"   Point 2: [1371,416]")
    print(f"   Point 3: [1352,1605]")
    print(f"   Point 4: [11,1585]")

    counting_config = {
        'type': 'zone',
        'points': zone_points.tolist()
    }

    # Draw zone on frame
    cv2.polylines(frame, [zone_points], True, (0, 255, 0), 3)
    cv2.putText(frame, "ZONE", (50, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    # Add point labels
    for i, point in enumerate(zone_points[0]):
        cv2.circle(frame, tuple(point[0]), 5, (0, 255, 0), -1)
        cv2.putText(frame, f"P{i+1}", tuple(point[0]),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

# Show the counting area
print("\n👆 Preview of your counting area:")
cv2_imshow(frame)

# Confirm
confirm = input("\n✅ Does this look correct? (y/n): ").lower()
if confirm == 'y':
    # Save configuration
    counting_config['method_name'] = 'LINE' if method == '1' else 'ZONE'
    with open('/content/potato_counter/counting_config.pkl', 'wb') as f:
        pickle.dump(counting_config, f)

    print(f"\n✅ Configuration saved!")
    print(f"   Method: {counting_config['method_name']}")
    if method == '1':
        print(f"   Line: {counting_config['start']} to {counting_config['end']}")
        print(f"   Enter direction: {counting_config['enter_direction']}")
    else:
        print(f"   Zone: 4-point polygon")
else:
    print("\n❌ Setup cancelled. You can manually adjust coordinates in the code.")

# ==================================================
# CELL 6: ZONE COUNTING SETUP (NEW)
# ==================================================

print("🎯 ZONE COUNTING SETUP - Count at the Door")
print("="*50)
print("We'll create a ZONE around the door area")
print("When people ENTER this zone = IN count")
print("When people EXIT this zone = OUT count")
print("="*50)

import cv2
import pickle
import numpy as np
from google.colab.patches import cv2_imshow

# Load video info
with open('/content/potato_counter/video_info.pkl', 'rb') as f:
    video_info = pickle.load(f)

# Read first frame
cap = cv2.VideoCapture(video_info['path'])
ret, frame = cap.read()
cap.release()

# Based on the track data, people cross around X=369
door_x = 180

# Create a zone around the door (a vertical strip)
zone_width = 100  # 50 pixels on each side of the door
zone_x1 = door_x - 50  # Left boundary
zone_x2 = door_x + 50  # Right boundary
zone_y1 = 400  # Top of zone (adjust based on your video)
zone_y2 = 700  # Bottom of zone (adjust based on your video)

print(f"\n📍 Door location: X = {door_x}")
print(f"📦 Counting Zone: X from {zone_x1} to {zone_x2}")
print(f"                  Y from {zone_y1} to {zone_y2}")

# Draw the zone on the frame
# Draw the door line
cv2.line(frame, (door_x, 0), (door_x, video_info['height']), (0, 255, 255), 2)
cv2.putText(frame, "DOOR", (door_x+10, 50), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 255), 2)

# Draw the counting zone (semi-transparent rectangle)
overlay = frame.copy()
cv2.rectangle(overlay, (zone_x1, zone_y1), (zone_x2, zone_y2), (0, 255, 0), -1)
frame = cv2.addWeighted(overlay, 0.3, frame, 0.7, 0)
cv2.rectangle(frame, (zone_x1, zone_y1), (zone_x2, zone_y2), (0, 255, 0), 3)
cv2.putText(frame, "COUNTING ZONE", (zone_x1, zone_y1-10),
            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

# Add inside/outside labels
cv2.putText(frame, "INSIDE", (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)
cv2.putText(frame, "OUTSIDE", (video_info['width']-150, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 0), 2)
cv2.putText(frame, "← ENTER", (door_x-200, 200), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
cv2.putText(frame, "EXIT →", (door_x+50, 200), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

print("\n👆 Preview of your counting zone:")
cv2_imshow(frame)

# Confirm
confirm = input("\n✅ Does this zone look correct? (y/n): ").lower()
if confirm != 'y':
    print("\n📏 Let's adjust the zone:")
    zone_x1 = int(input(f"Enter left X (current {zone_x1}): ") or zone_x1)
    zone_x2 = int(input(f"Enter right X (current {zone_x2}): ") or zone_x2)
    zone_y1 = int(input(f"Enter top Y (current {zone_y1}): ") or zone_y1)
    zone_y2 = int(input(f"Enter bottom Y (current {zone_y2}): ") or zone_y2)

# Save zone configuration
config = {
    'type': 'zone',
    'door_x': door_x,
    'zone': [zone_x1, zone_y1, zone_x2, zone_y2],
    'method_name': 'ZONE'
}

with open('/content/potato_counter/counting_config.pkl', 'wb') as f:
    pickle.dump(config, f)

print(f"\n✅ Zone configuration saved!")
print(f"   Zone: [{zone_x1}, {zone_y1}] to [{zone_x2}, {zone_y2}]")

# ==================================================
# CELL 7: COUNT MEN CARRYING BAGS! (Main Processing)
# ==================================================

print("👨 STARTING COUNT - MEN CARRYING BAGS ONLY")
print("="*50)
print("Class 0: men_carrying_bag (🟢 GREEN - COUNTED)")
print("Class 1: men_without_bag (🔴 RED - IGNORED)")
print("="*50)

import cv2
import pickle
import numpy as np
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
from IPython.display import Video
import os
from datetime import datetime

# Load your trained model (V2 - the good one!)
model = YOLO('/content/runs/detect/men_with_bags_model_v2/weights/best.pt')

# Load video info
with open('/content/potato_counter/video_info.pkl', 'rb') as f:
    video_info = pickle.load(f)

# Load counting configuration
with open('/content/potato_counter/counting_config.pkl', 'rb') as f:
    config = pickle.load(f)

video_path = video_info['path']
fps = video_info['fps']
width = video_info['width']
height = video_info['height']
total_frames = video_info['total_frames']

# Get line coordinates
line_start = config['start']
line_end = config['end']
enter_direction = config['enter_direction']

print(f"\n📊 Counting Configuration:")
print(f"   Line: {line_start} to {line_end}")
print(f"   Enter direction: {enter_direction} (right to left = IN)")
print(f"   Video: {os.path.basename(video_path)}")
print(f"   Duration: {video_info['duration']:.2f} seconds")
print(f"   Total frames: {total_frames}")

# Setup video writer
output_path = '/content/potato_counter/output/counted_video.mp4'
out = cv2.VideoWriter(output_path,
                      cv2.VideoWriter_fourcc(*'mp4v'),
                      fps, (width, height))

# Tracking variables
tracked_objects = {}  # {track_id: {'last_x': 0, 'counted': False}}
in_count = 0
out_count = 0
frame_count = 0

print("\n🔄 Processing video...")
print("(This will show progress every 100 frames)")

# Open video
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run detection with tracking (using confidence 0.3 for good balance)
    results = model.track(frame, persist=True, conf=0.3, iou=0.5, verbose=False)

    # Draw the counting line
    cv2.line(frame, line_start, line_end, (0, 255, 255), 3)
    cv2.putText(frame, "COUNTING LINE", (line_start[0]+10, line_start[1]-10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 255), 2)

    # Add direction labels
    cv2.putText(frame, "ENTER →", (50, 100),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    cv2.putText(frame, "← EXIT", (width-150, 100),
                cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

    # Display counts
    cv2.putText(frame, f'IN (with bags): {in_count}', (50, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.putText(frame, f'OUT (with bags): {out_count}', (50, 150),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

    # Process detections
    if results[0].boxes.id is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        track_ids = results[0].boxes.id.cpu().numpy()
        class_ids = results[0].boxes.cls.cpu().numpy()
        confidences = results[0].boxes.conf.cpu().numpy()

        for box, track_id, class_id, conf in zip(boxes, track_ids, class_ids, confidences):
            class_id = int(class_id)

            # Get center point
            center_x = int((box[0] + box[2]) / 2)
            center_y = int((box[1] + box[3]) / 2)

            # ONLY COUNT CLASS 0 (men_carrying_bag)
            if class_id == 0:  # men_carrying_bag
                # Track line crossing
                if track_id not in tracked_objects:
                    tracked_objects[track_id] = {'last_x': center_x, 'counted': False}
                else:
                    last_x = tracked_objects[track_id]['last_x']
                    line_x = line_start[0]  # Use X coordinate of line

                    # Check for line crossing
                    if not tracked_objects[track_id]['counted']:
                        # Right to left crossing (entering)
                        if last_x > line_x >= center_x and enter_direction == 'right_to_left':
                            in_count += 1
                            tracked_objects[track_id]['counted'] = True
                            print(f"📥 Man with bag {int(track_id)} ENTERED at frame {frame_count} (conf: {conf:.2f})")

                        # Left to right crossing (exiting)
                        elif last_x < line_x <= center_x and enter_direction == 'left_to_right':
                            in_count += 1
                            tracked_objects[track_id]['counted'] = True
                            print(f"📥 Man with bag {int(track_id)} ENTERED at frame {frame_count} (conf: {conf:.2f})")

                        # Opposite direction (exits)
                        elif last_x < line_x <= center_x and enter_direction == 'right_to_left':
                            out_count += 1
                            tracked_objects[track_id]['counted'] = True
                            print(f"📤 Man with bag {int(track_id)} EXITED at frame {frame_count} (conf: {conf:.2f})")

                        elif last_x > line_x >= center_x and enter_direction == 'left_to_right':
                            out_count += 1
                            tracked_objects[track_id]['counted'] = True
                            print(f"📤 Man with bag {int(track_id)} EXITED at frame {frame_count} (conf: {conf:.2f})")

                    tracked_objects[track_id]['last_x'] = center_x

                # Draw GREEN box for men with bags
                cv2.rectangle(frame, (int(box[0]), int(box[1])),
                             (int(box[2]), int(box[3])), (0, 255, 0), 3)
                cv2.putText(frame, f'BAG MAN {int(track_id)}',
                           (int(box[0]), int(box[1])-10),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
                cv2.putText(frame, f'{conf:.2f}',
                           (int(box[0]), int(box[3])+20),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

                # Draw trajectory dot
                cv2.circle(frame, (center_x, center_y), 5, (0, 255, 0), -1)

            else:  # class_id == 1 (men_without_bag)
                # Draw RED box for men without bags (not counted)
                cv2.rectangle(frame, (int(box[0]), int(box[1])),
                             (int(box[2]), int(box[3])), (0, 0, 255), 1)
                cv2.putText(frame, 'NO BAG',
                           (int(box[0]), int(box[1])-10),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1)

    # Write frame
    out.write(frame)
    frame_count += 1

    # Progress update
    if frame_count % 100 == 0:
        progress = (frame_count / total_frames) * 100
        print(f"   Progress: {progress:.1f}% - IN: {in_count}, OUT: {out_count}")

# Clean up
cap.release()
out.release()

print("\n" + "="*50)
print("✅ COUNTING COMPLETE!")
print("="*50)
print(f"📊 FINAL RESULTS:")
print(f"   Men with bags IN:  {in_count}")
print(f"   Men with bags OUT: {out_count}")
print(f"   Net change: {in_count - out_count}")
print(f"   Total unique men with bags tracked: {len([k for k in tracked_objects if tracked_objects[k]['counted']])}")

# ==================================================
# CELL 7.5: DIAGNOSTIC - Check Why No Detections
# ==================================================

import cv2
from ultralytics import YOLO
from google.colab.patches import cv2_imshow
import pickle

# Load model and video
model = YOLO('/content/runs/detect/men_with_bags_model_v2/weights/best.pt')

with open('/content/potato_counter/video_info.pkl', 'rb') as f:
    video_info = pickle.load(f)

# Check a few frames from the video
cap = cv2.VideoCapture(video_info['path'])

print("🔍 CHECKING VIDEO FRAMES FOR DETECTIONS")

# Check frames at different points
frame_positions = [100, 300, 500]  # Check frames 100, 300, 500

for frame_num in frame_positions:
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)
    ret, frame = cap.read()

    if ret:
        print(f"\n📸 Frame {frame_num}:")

        # Try with different confidence thresholds
        for conf_thresh in [0.1, 0.05, 0.01]:
            results = model(frame, conf=conf_thresh)
            boxes = results[0].boxes

            if boxes is not None and len(boxes) > 0:
                print(f"   ✅ Found {len(boxes)} detections at conf {conf_thresh}")
                for box in boxes:
                    class_id = int(box.cls.cpu().numpy())
                    conf = float(box.conf.cpu().numpy())
                    class_name = "men_carrying_bag" if class_id == 0 else "men_without_bag"
                    print(f"      - {class_name}: confidence {conf:.3f}")

                # Show the frame with detections
                annotated = results[0].plot()
                cv2_imshow(annotated)
                break
            else:
                print(f"   ❌ No detections at conf {conf_thresh}")

        if boxes is None or len(boxes) == 0:
            print("   Displaying raw frame (no detections):")
            cv2_imshow(frame)

cap.release()

# ==================================================
# CELL 7.6: Try Processing with Very Low Confidence
# ==================================================

print("🔄 REPROCESSING WITH VERY LOW CONFIDENCE (0.01)")

# Reload model
model = YOLO('/content/runs/detect/men_with_bags_model_v2/weights/best.pt')

# Reprocess with very low confidence
cap = cv2.VideoCapture(video_info['path'])
frame_count = 0
total_frames = video_info['total_frames']

men_with_bags_found = 0
men_without_bags_found = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run with very low confidence
    results = model(frame, conf=0.01)
    boxes = results[0].boxes

    if boxes is not None and len(boxes) > 0:
        for box in boxes:
            class_id = int(box.cls.cpu().numpy())
            conf = float(box.conf.cpu().numpy())

            if class_id == 0:  # men_carrying_bag
                men_with_bags_found += 1
                if men_with_bags_found == 1:  # Show first detection
                    print(f"\n✅ FIRST DETECTION at frame {frame_count}:")
                    print(f"   Confidence: {conf:.3f}")
                    annotated = results[0].plot()
                    cv2_imshow(annotated)
            else:
                men_without_bags_found += 1

    frame_count += 1
    if frame_count % 100 == 0:
        print(f"   Processed {frame_count}/{total_frames} frames...")

cap.release()

print(f"\n📊 SCANNING RESULTS:")
print(f"   Men with bags found (at conf 0.01): {men_with_bags_found}")
print(f"   Men without bags found: {men_without_bags_found}")